[package]
name = "envgg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
futures = "0.3.31"
secret-service = { version = "5.1.0", features = ["rt-tokio-crypto-rust"] }
tokio = { version = "1.48.0", features = ["full"] }
